version: '3.8'
services:
  Dread Music Bot:
    image: no image
    container_name: Dread Music Bot
    restart: always
    ports:
      - 33333:33333
    environment:
      TOKEN: "your_token"
      PREFIX: "+"
      PLAYING: "+help | music"
      EMBEDS_COLOR: "#FFFFFF"
      DEFAULT_VOLUME: 50
      MAX_VOLUME: 100
      AUTO_LEAVE: "true"
      AUTO_LEAVE_COOLDOWN: 5000
      DISPLAY_VOICE_STATE: "true"
      TEXT_QUERY_TYPE: "youtubeSearch"
      URL_QUERY_TYPE: "auto"
      DP_FORCE_YTDL_MOD: "play-dl"